---
- name: Install Nginx
  apt: name=nginx state=latest update_cache={{ update_apt_cache }}
  tags:
    - smarty
    - nginx

- name: Compile Nginx SSL configuration
  template: src=nginx.ssl.conf.j2
            dest=/etc/nginx/snippets/ssl-{{ application_domain }}.conf
            mode=0644
  notify: nginx restart
  tags:
    - smarty
    - nginx

- name: Copy Nginx SSL params file
  copy: src=ssl-params.conf
        dest=/etc/nginx/snippets/ssl-params.conf
        mode=0644
  notify: nginx restart
  tags:
    - smarty
    - nginx

- name: Compile Nginx configuration
  template: src=nginx.conf.j2
            dest=/etc/nginx/sites-available/{{ application_domain }}.conf
            mode=0644
  notify: nginx restart
  tags:
    - smarty
    - nginx

- name: Create symlink to Smarty service
  file: src=/etc/nginx/sites-available/{{ application_domain }}.conf
        dest=/etc/nginx/sites-enabled/{{ application_domain }}.conf
        state=link
  notify: nginx reload
  tags:
    - smarty
    - nginx

- name: Remove default Nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags:
    - smarty
    - nginx

- name: Ensure that the Nginx service is running
  service: name=nginx state=started enabled=yes
  tags:
    - smarty
    - nginx
