---

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  tags:
    - smarty
    - push_updates

- name: Delete logs
  file:
    path: "{{ log_path }}/"
    state: absent
  args:
    removes: "{{ log_path }}"
  tags: smarty

- name: Create the application log folder
  file: path={{ log_path }}
        mode=0774
        state=directory
        owner={{ app_user }}
        group={{ app_group }}
  tags: smarty

#- name: Create the application log file
#  file: path={{ log_path }}
#        owner={{ app_user }}
#        group={{ app_group }}
#        mode=0664
#        state=touch
#  tags: smarty
